--
-- PostgreSQL database dump
--

-- Dumped from database version 14.18 (Ubuntu 14.18-0ubuntu0.22.04.1)
-- Dumped by pg_dump version 14.18 (Ubuntu 14.18-0ubuntu0.22.04.1)

SET statement_timeout = 0;

SET lock_timeout = 0;

SET idle_in_transaction_session_timeout = 0;

SET client_encoding = 'UTF8';

SET standard_conforming_strings = on;

SELECT pg_catalog.set_config ('search_path', '', false);

SET check_function_bodies = false;

SET xmloption = content;

SET client_min_messages = warning;

SET row_security = off;

--
-- Name: postgis; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS postgis WITH SCHEMA public;

--
-- Name: EXTENSION postgis; Type: COMMENT; Schema: -; Owner:
--

COMMENT ON EXTENSION postgis IS 'PostGIS geometry and geography spatial types and functions';

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: chat_message; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.chat_message (
    id bigint NOT NULL,
    content character varying(255),
    receiver bigint,
    sender bigint,
    status character varying(255),
    "timestamp" timestamp(6) with time zone,
    connection_id bigint,
    CONSTRAINT chat_message_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'SENT'::character varying, 'DELIVERED'::character varying, 'READ'::character varying, 'FAILED'::character varying, 'DELETED'::character varying])::text[])))
);

ALTER TABLE public.chat_message OWNER TO postgres;

--
-- Name: chat_message_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.chat_message
ALTER COLUMN id
ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_message_id_seq START
    WITH
        1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

--
-- Name: connection; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.connection (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    last_message_timestamp timestamp(6) with time zone,
    number_of_messages integer NOT NULL,
    receiver_id bigint,
    receiver_status character varying(255),
    sender_id bigint,
    sender_status character varying(255),
    CONSTRAINT connection_receiver_status_check CHECK (((receiver_status)::text = ANY ((ARRAY['ACCEPTED'::character varying, 'REJECTED'::character varying, 'PENDING'::character varying, 'BLOCKED'::character varying])::text[]))),
    CONSTRAINT connection_sender_status_check CHECK (((sender_status)::text = ANY ((ARRAY['ACCEPTED'::character varying, 'REJECTED'::character varying, 'PENDING'::character varying, 'BLOCKED'::character varying])::text[])))
);

ALTER TABLE public.connection OWNER TO postgres;

--
-- Name: connection_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.connection
ALTER COLUMN id
ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.connection_id_seq START
    WITH
        1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

--
-- Name: gender; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.gender (
    id bigint NOT NULL,
    name character varying(255)
);

ALTER TABLE public.gender OWNER TO postgres;

--
-- Name: gender_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.gender
ALTER COLUMN id
ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.gender_id_seq START
    WITH
        1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

--
-- Name: interest; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.interest (
    id bigint NOT NULL,
    name character varying(255)
);

ALTER TABLE public.interest OWNER TO postgres;

--
-- Name: interest_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.interest
ALTER COLUMN id
ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.interest_id_seq START
    WITH
        1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

--
-- Name: location; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.location (
    id bigint NOT NULL,
    accuracy double precision NOT NULL,
    point public.geography (Point, 4326),
    "timestamp" timestamp(6)
    with
        time zone
);

ALTER TABLE public.location OWNER TO postgres;

--
-- Name: location_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.location
ALTER COLUMN id
ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.location_id_seq START
    WITH
        1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

--
-- Name: matching_filter; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.matching_filter (
    id bigint NOT NULL,
    gender_preference character varying(255),
    highest_age integer,
    interest_score integer,
    lowest_age integer,
    match_limit integer,
    nationality_score integer,
    personality_score integer,
    purpose_score integer,
    radius integer,
    user_id bigint
);

ALTER TABLE public.matching_filter OWNER TO postgres;

--
-- Name: matching_filter_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.matching_filter
ALTER COLUMN id
ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.matching_filter_id_seq START
    WITH
        1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

--
-- Name: named_location; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.named_location (
    id bigint NOT NULL,
    accuracy double precision NOT NULL,
    name character varying(255),
    point public.geography (Point, 4326)
);

ALTER TABLE public.named_location OWNER TO postgres;

--
-- Name: named_location_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.named_location
ALTER COLUMN id
ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.named_location_id_seq START
    WITH
        1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

--
-- Name: nationality; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.nationality (
    id bigint NOT NULL,
    name character varying(255)
);

ALTER TABLE public.nationality OWNER TO postgres;

--
-- Name: nationality_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.nationality
ALTER COLUMN id
ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.nationality_id_seq START
    WITH
        1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

--
-- Name: personality; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.personality (
    id bigint NOT NULL,
    name character varying(255)
);

ALTER TABLE public.personality OWNER TO postgres;

--
-- Name: personality_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.personality
ALTER COLUMN id
ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.personality_id_seq START
    WITH
        1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

--
-- Name: purpose; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.purpose (
    id bigint NOT NULL,
    name character varying(255)
);

ALTER TABLE public.purpose OWNER TO postgres;

--
-- Name: purpose_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.purpose
ALTER COLUMN id
ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.purpose_id_seq START
    WITH
        1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

--
-- Name: user_interest; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_interest (
    user_id bigint NOT NULL,
    interest_id bigint NOT NULL
);

ALTER TABLE public.user_interest OWNER TO postgres;

--
-- Name: user_location; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_location (
    id bigint NOT NULL,
    location_id bigint NOT NULL,
    user_id bigint NOT NULL
);

ALTER TABLE public.user_location OWNER TO postgres;

--
-- Name: user_location_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.user_location
ALTER COLUMN id
ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_location_id_seq START
    WITH
        1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

--
-- Name: user_personality; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_personality (
    user_id bigint NOT NULL,
    personality_id bigint NOT NULL
);

ALTER TABLE public.user_personality OWNER TO postgres;

--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    birth_date timestamp(6)
    with
        time zone,
        email character varying(255) NOT NULL,
        last_seen timestamp(6)
    with
        time zone,
        password_hash character varying(255) NOT NULL,
        profile_image_name character varying(255),
        user_description text,
        username character varying(255) NOT NULL,
        gender_id bigint,
        location_id bigint,
        nationality_id bigint,
        purpose_id bigint
);

ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users
ALTER COLUMN id
ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq START
    WITH
        1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

--
-- Data for Name: chat_message; Type: TABLE DATA; Schema: public; Owner: postgres
--


COPY public.chat_message (id, content, receiver, sender, status, "timestamp", connection_id) FROM stdin;
\.

--
-- Data for Name: connection; Type: TABLE DATA; Schema: public; Owner: postgres
--


COPY public.connection (id, created_at, last_message_timestamp, number_of_messages, receiver_id, receiver_status, sender_id, sender_status) FROM stdin;
\.

--
-- Data for Name: gender; Type: TABLE DATA; Schema: public; Owner: postgres
--


COPY public.gender (id, name) FROM stdin;
1	Non-Binary
2	Unspecified
3	Male
4	Female
\.

--
-- Data for Name: interest; Type: TABLE DATA; Schema: public; Owner: postgres
--


COPY public.interest (id, name) FROM stdin;
1	Finance
2	Sports
3	Food
4	Billiards
5	Investing
6	Drink
7	Board Games
8	Campaigns
9	Economy
10	Basketball
11	Football
12	Restaurant
13	Video Games
14	Elections
15	Tourism
16	Travel
17	Politics
18	Hunting
19	Museum
\.

--
-- Data for Name: location; Type: TABLE DATA; Schema: public; Owner: postgres
--


COPY public.location (id, accuracy, point, "timestamp") FROM stdin;
\.

--
-- Data for Name: matching_filter; Type: TABLE DATA; Schema: public; Owner: postgres
--


COPY public.matching_filter (id, gender_preference, highest_age, interest_score, lowest_age, match_limit, nationality_score, personality_score, purpose_score, radius, user_id) FROM stdin;
\.

--
-- Data for Name: named_location; Type: TABLE DATA; Schema: public; Owner: postgres
--


COPY public.named_location (id, accuracy, name, point) FROM stdin;
1	11.1	Pärnu	0101000020E6100000EF384547729939408B6CE7FBA9214D40
2	16.5	Keila	0101000020E61000009A999999995938403333333333B34D40
3	9.7	Maardu	0101000020E610000014D044D8F0D4384009F9A067B3B24D40
4	12	Jõhvi	0101000020E6100000D712F241CF063B4031992A1895344D40
5	14.2	Rapla	0101000020E610000096218E75717B38405396218E75794D40
6	8.9	Viljandi	0101000020E61000009A99999999093A40E3361AC05B604D40
7	12.5	Tallinn	0101000020E6100000FE43FAEDEBC038400E2DB29DEFB74D40
8	15	Tartu	0101000020E61000000D71AC8BDBB83A401C7C613255304D40
9	10	Võru	0101000020E61000002EFF21FDF6453B40CEAACFD556E44C40
10	13.3	Narva	0101000020E61000000000000000F03A40545227A089884D40
\.

--
-- Data for Name: nationality; Type: TABLE DATA; Schema: public; Owner: postgres
--


COPY public.nationality (id, name) FROM stdin;
1	Italian
2	San Marinese
3	Norwegian
4	German
5	Hungarian
6	Slovak
7	Russian
8	Serbian
9	Swedish
10	Turkish
11	Slovenian
12	Swiss
13	Ukrainian
14	Maltese
15	French
16	Portuguese
17	Andorran
18	Latvian
19	Liechtensteiner
20	Spanish
21	Bosnian
22	Finnish
23	Moldovan
24	Austrian
25	Polish
26	Cypriot
27	Vatican
28	Romanian
29	Albanian
30	Lithuanian
31	Bulgarian
32	Monégasque
33	Croatian
34	Estonian
35	Belgian
36	Irish
37	Kosovar
38	Icelandic
39	Luxembourgish
40	Belarusian
41	Montenegrin
42	North Macedonian
43	Danish
44	Czech
45	Dutch
46	Greek
\.

--
-- Data for Name: personality; Type: TABLE DATA; Schema: public; Owner: postgres
--


COPY public.personality (id, name) FROM stdin;
1	Loyal
2	Spontaneous
3	Curious
4	Organized
5	Outgoing
6	Creative
7	Exuberant
8	Honorable
9	Tolerant
10	Sharp
11	Confident
12	Thoughtful
13	Analytical
14	Kind
15	Observant
16	Idealistic
17	Theoretical
18	Decisive
19	Conscientious
20	Ambitious
21	Persistent
22	Patient
23	Courageous
24	Honest
25	Compassionate
26	Independent
27	Flexible
28	Disciplined
29	Resilient
30	Quiet
31	Emotional
32	Humble
\.

--
-- Data for Name: purpose; Type: TABLE DATA; Schema: public; Owner: postgres
--


COPY public.purpose (id, name) FROM stdin;
1	Study
2	Gaming
3	Companionship
4	Interacting
5	Professional
\.

--
-- Data for Name: spatial_ref_sys; Type: TABLE DATA; Schema: public; Owner: postgres
--


COPY public.spatial_ref_sys (srid, auth_name, auth_srid, srtext, proj4text) FROM stdin;
\.

--
-- Data for Name: user_interest; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.user_interest (user_id, interest_id) FROM stdin;
\.

--
-- Data for Name: user_location; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.user_location (id, location_id, user_id) FROM stdin;
\.

--
-- Data for Name: user_personality; Type: TABLE DATA; Schema: public; Owner: postgres
--


COPY public.user_personality (user_id, personality_id) FROM stdin;
\.

--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--


COPY public.users (id, birth_date, email, last_seen, password_hash, profile_image_name, user_description, username, gender_id, location_id, nationality_id, purpose_id) FROM stdin;
\.

--
-- Name: chat_message_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval ( 'public.chat_message_id_seq', 1, false );

--
-- Name: connection_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval ( 'public.connection_id_seq', 1, false );

--
-- Name: gender_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval ( 'public.gender_id_seq', 4, true );

--
-- Name: interest_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval ( 'public.interest_id_seq', 19, true );

--
-- Name: location_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval ( 'public.location_id_seq', 1, false );

--
-- Name: matching_filter_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval (
        'public.matching_filter_id_seq', 1, false
    );

--
-- Name: named_location_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval (
        'public.named_location_id_seq', 10, true
    );

--
-- Name: nationality_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval ( 'public.nationality_id_seq', 46, true );

--
-- Name: personality_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval ( 'public.personality_id_seq', 32, true );

--
-- Name: purpose_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval ( 'public.purpose_id_seq', 5, true );

--
-- Name: user_location_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval ( 'public.user_location_id_seq', 1, false );

--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval ( 'public.users_id_seq', 1, false );

--
-- Name: chat_message chat_message_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chat_message
ADD CONSTRAINT chat_message_pkey PRIMARY KEY (id);

--
-- Name: connection connection_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.connection
ADD CONSTRAINT connection_pkey PRIMARY KEY (id);

--
-- Name: gender gender_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.gender
ADD CONSTRAINT gender_pkey PRIMARY KEY (id);

--
-- Name: interest interest_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.interest
ADD CONSTRAINT interest_pkey PRIMARY KEY (id);

--
-- Name: location location_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.location
ADD CONSTRAINT location_pkey PRIMARY KEY (id);

--
-- Name: matching_filter matching_filter_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.matching_filter
ADD CONSTRAINT matching_filter_pkey PRIMARY KEY (id);

--
-- Name: named_location named_location_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.named_location
ADD CONSTRAINT named_location_pkey PRIMARY KEY (id);

--
-- Name: nationality nationality_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.nationality
ADD CONSTRAINT nationality_pkey PRIMARY KEY (id);

--
-- Name: personality personality_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.personality
ADD CONSTRAINT personality_pkey PRIMARY KEY (id);

--
-- Name: purpose purpose_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.purpose
ADD CONSTRAINT purpose_pkey PRIMARY KEY (id);

--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);

--
-- Name: user_location uk9jw1di7ynibylp5xt7bl8f5s3; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_location
ADD CONSTRAINT uk9jw1di7ynibylp5xt7bl8f5s3 UNIQUE (user_id);

--
-- Name: gender ukjdyxf8c9k9656frmqjb67cgo3; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.gender
ADD CONSTRAINT ukjdyxf8c9k9656frmqjb67cgo3 UNIQUE (name);

--
-- Name: interest ukn9khibjfvt2sanahgb13qslgd; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.interest
ADD CONSTRAINT ukn9khibjfvt2sanahgb13qslgd UNIQUE (name);

--
-- Name: nationality ukq0ebuvmrq0bhf2nvqlywk3eq2; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.nationality
ADD CONSTRAINT ukq0ebuvmrq0bhf2nvqlywk3eq2 UNIQUE (name);

--
-- Name: users ukr43af9ap4edm43mmtq01oddj6; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);

--
-- Name: matching_filter ukr99o72r4ur8i4rjj29gabecs6; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.matching_filter
ADD CONSTRAINT ukr99o72r4ur8i4rjj29gabecs6 UNIQUE (user_id);

--
-- Name: user_interest user_interest_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_interest
ADD CONSTRAINT user_interest_pkey PRIMARY KEY (user_id, interest_id);

--
-- Name: user_location user_location_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_location
ADD CONSTRAINT user_location_pkey PRIMARY KEY (id);

--
-- Name: user_personality user_personality_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_personality
ADD CONSTRAINT user_personality_pkey PRIMARY KEY (user_id, personality_id);

--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
ADD CONSTRAINT users_pkey PRIMARY KEY (id);

--
-- Name: user_personality fk1l2sd6xmdw78lavpmi2lrau6s; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_personality
ADD CONSTRAINT fk1l2sd6xmdw78lavpmi2lrau6s FOREIGN KEY (user_id) REFERENCES public.users (id);

--
-- Name: chat_message fk3hfdp2jae0v4e524x3txwxvcs; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chat_message
ADD CONSTRAINT fk3hfdp2jae0v4e524x3txwxvcs FOREIGN KEY (connection_id) REFERENCES public.connection (id);

--
-- Name: users fk5yoot2ex043mrua6vayv2ecc1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
ADD CONSTRAINT fk5yoot2ex043mrua6vayv2ecc1 FOREIGN KEY (location_id) REFERENCES public.user_location (id);

--
-- Name: user_interest fk97yodomof0ffqwpnt9obp1l6c; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_interest
ADD CONSTRAINT fk97yodomof0ffqwpnt9obp1l6c FOREIGN KEY (user_id) REFERENCES public.users (id);

--
-- Name: user_interest fkb2c20k2dqknrm5t337typ3s1b; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_interest
ADD CONSTRAINT fkb2c20k2dqknrm5t337typ3s1b FOREIGN KEY (interest_id) REFERENCES public.interest (id);

--
-- Name: user_location fkc0weugwtyidbytmdye09cp0gl; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_location
ADD CONSTRAINT fkc0weugwtyidbytmdye09cp0gl FOREIGN KEY (location_id) REFERENCES public.location (id);

--
-- Name: matching_filter fkcfbpg3fwh6aaefn1an4ssyoi9; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.matching_filter
ADD CONSTRAINT fkcfbpg3fwh6aaefn1an4ssyoi9 FOREIGN KEY (user_id) REFERENCES public.users (id);

--
-- Name: users fkcfpa75yty0jsdot2qie0dbexn; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
ADD CONSTRAINT fkcfpa75yty0jsdot2qie0dbexn FOREIGN KEY (purpose_id) REFERENCES public.purpose (id);

--
-- Name: user_location fkjxhhctinrouub93yin6vgvqr4; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_location
ADD CONSTRAINT fkjxhhctinrouub93yin6vgvqr4 FOREIGN KEY (user_id) REFERENCES public.users (id);

--
-- Name: user_personality fkl9prgd0dv2mf63ecvqlc5g28j; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_personality
ADD CONSTRAINT fkl9prgd0dv2mf63ecvqlc5g28j FOREIGN KEY (personality_id) REFERENCES public.personality (id);

--
-- Name: users fklny21mholiaykmo8js78d3o36; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
ADD CONSTRAINT fklny21mholiaykmo8js78d3o36 FOREIGN KEY (nationality_id) REFERENCES public.nationality (id);

--
-- Name: users fko0h29eo9e4y4wvd5yh0sn03rp; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
ADD CONSTRAINT fko0h29eo9e4y4wvd5yh0sn03rp FOREIGN KEY (gender_id) REFERENCES public.gender (id);

--
-- PostgreSQL database dump complete
--