# =========================
# Spring Boot Dev Settings
# =========================

server.port=8080
spring.application.name=backend
server.address=0.0.0.0

# Log SQL query parameters

# logging.level.com.kood.backend=DEBUG
# logging.level.org.springframework.web=DEBUG
# logging.level.org.hibernate.SQL=DEBUG

logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG

logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.hibernate.engine.transaction=TRACE
logging.level.org.hibernate.event=TRACE
logging.level.org.hibernate.persister.entity=TRACE

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.http.converter.json=TRACE

# =========================
# Database Configuration
# =========================

spring.datasource.url=jdbc:postgresql://localhost:5432/match-me
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.database=POSTGRESQL
spring.sql.init.platform=postgres

# =========================
# JPA & Hibernate
# =========================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.spatial.enabled=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# =========================
# Security Configuration
# =========================

# Disable Spring Boot’s default security login
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# Leave empty if you're handling auth manually (e.g., with JWT)
spring.security.user.name=
spring.security.user.password=
#logging.level.root=DEBUG
# =========================
# JWT Configuration (Dev)
# =========================
mockUsers.skip=true

media.storage.location=../media
# launching from the backend directory go back up and inside media folder

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# <mvn spring-boot:run -Dspring-boot.run.profiles=dev -Dspring-boot.run.arguments="--mockUsers.skip=true"> inside backend folder to run dev environment without generating users,
# do not add the argument if you want to generate test users
kood.app.jwtExpirationMs=36000000
# 1 hour
kood.app.jwtSecret=verylongpasswordrequiredbecauseHS256needstobeatleast256bitsinsizeotherwisbigerror
